"""initial schema

Revision ID: 118b2f59d296
Revises: 
Create Date: 2026-09-12 02:47:54.883293
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '118b2f59d296'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_events',
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('contract', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('tx_key', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('handle_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tx_hash', 'log_index')
    )
    op.create_index(op.f('ix_blockchain_events_tx_key'), 'blockchain_events', ['tx_key'], unique=False)
    op.create_table('kv_cursors',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('privy_did', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('wallet_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_index(op.f('ix_users_privy_did'), 'users', ['privy_did'], unique=True)
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'route', 'key')
    )
    op.create_table('intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clarifying_question', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('ai_model', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intents_customer_id'), 'intents', ['customer_id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('trade', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('areas', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('base_rate_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('available_dates', postgresql.ARRAY(sa.Date()), server_default='{}', nullable=False),
    sa.Column('seeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_providers_trade'), 'providers', ['trade'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intent_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('trade_offs', sa.Text(), nullable=True),
    sa.Column('trust_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id', 'provider_id', 'version', name='ux_quotes_version')
    )
    op.create_index(op.f('ix_quotes_intent_id'), 'quotes', ['intent_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tx_key', sa.String(length=66), nullable=False),
    sa.Column('intent_id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rail', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('display_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('fx_rate_ngn_per_usdc', sa.Integer(), nullable=True),
    sa.Column('dispute_window_s', sa.Integer(), nullable=True),
    sa.Column('authorization_offer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('seeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id'),
    sa.UniqueConstraint('tx_key')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_provider_id'), 'transactions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_transactions_state'), 'transactions', ['state'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('from_state', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('to_state', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'seq', name='ux_audit_seq')
    )
    op.create_index(op.f('ix_audit_events_transaction_id'), 'audit_events', ['transaction_id'], unique=False)
    op.create_table('chain_txs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('nonce', sa.BigInteger(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_chain_txs_status'), 'chain_txs', ['status'], unique=False)
    op.create_index(op.f('ix_chain_txs_transaction_id'), 'chain_txs', ['transaction_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('scope_item', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(length=280), nullable=True),
    sa.Column('anchor_tx_id', sa.BigInteger(), nullable=True),
    sa.Column('anchored_tx', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'sha256', name='ux_evidence_hash')
    )
    op.create_index(op.f('ix_evidence_transaction_id'), 'evidence', ['transaction_id'], unique=False)
    op.create_table('fulfillments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deliverable_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=True),
    sa.Column('submit_tx', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('human_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('credential', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('nullifier', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('signal_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=True),
    sa.Column('protocol_version', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action', 'nullifier', 'scope_key', name='ux_human_checks')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('rail', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rail', 'direction', 'external_ref', name='ux_payments_ref')
    )
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.create_table('authorizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('typed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('signer', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('authorization_hash', sa.String(length=66), nullable=False),
    sa.Column('max_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('scope_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('provider_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('human_check_id', sa.Uuid(), nullable=False),
    sa.Column('policy_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['human_check_id'], ['human_checks.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_hash'),
    sa.UniqueConstraint('transaction_id', 'version', name='ux_authorizations_version')
    )
    op.create_index(op.f('ix_authorizations_transaction_id'), 'authorizations', ['transaction_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('filed_by', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('complaint_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('human_check_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['human_check_id'], ['human_checks.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_transaction_id'), 'complaints', ['transaction_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('resolution_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dispute_id', sa.Uuid(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('remedy', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('provider_bps', sa.Integer(), nullable=False),
    sa.Column('to_provider_minor', sa.BigInteger(), nullable=False),
    sa.Column('to_customer_minor', sa.BigInteger(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('cited_evidence_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('input_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('outcome_hash', sa.String(length=66), nullable=False),
    sa.Column('accept_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispute_id'),
    sa.UniqueConstraint('outcome_hash')
    )
    op.create_table('resolution_acceptances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('typed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['resolution_proposals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'user_id', name='ux_acceptance')
    )
    op.create_index(op.f('ix_resolution_acceptances_proposal_id'), 'resolution_acceptances', ['proposal_id'], unique=False)
    # ### end Alembic commands ###

    # --- beyond the table definitions: insert-only enforcement, hot paths and shape checks (schematics 4.3) ---
    op.execute("""
        CREATE OR REPLACE FUNCTION forbid_update_delete() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION '% is insert-only', TG_TABLE_NAME; END $$;
    """)
    for table in ("authorizations", "complaints", "resolution_acceptances", "audit_events"):
        op.execute(f"""
            CREATE TRIGGER {table}_insert_only BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION forbid_update_delete();
        """)
    op.execute("""
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'intentra_app') THEN
            REVOKE UPDATE, DELETE ON authorizations, complaints, resolution_acceptances, audit_events FROM intentra_app;
          END IF;
        END $$;
    """)
    op.execute("CREATE INDEX ix_tx_state_release ON transactions (state, release_after)")
    op.execute("CREATE INDEX ix_outbox_queue ON chain_txs (status, id) WHERE status IN ('QUEUED', 'SENT')")
    op.execute("CREATE INDEX ix_providers_areas ON providers USING gin (areas)")
    op.execute("ALTER TABLE transactions ADD CONSTRAINT ck_transactions_tx_key CHECK (tx_key ~ '^0x[0-9a-f]{64}$')")
    op.execute("ALTER TABLE resolution_proposals ADD CONSTRAINT ck_proposal_bps CHECK (provider_bps BETWEEN 0 AND 10000)")
    op.execute("ALTER TABLE resolution_proposals ADD CONSTRAINT ck_proposal_amounts "
               "CHECK (to_provider_minor >= 0 AND to_customer_minor >= 0)")
    op.execute("ALTER TABLE evidence ADD CONSTRAINT ck_evidence_bytes CHECK (bytes >= 0)")
    op.execute("ALTER TABLE human_checks ADD CONSTRAINT ck_human_checks_nullifier CHECK (nullifier >= 0)")


def downgrade() -> None:
    for table in ("authorizations", "complaints", "resolution_acceptances", "audit_events"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_insert_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS forbid_update_delete()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolution_acceptances_proposal_id'), table_name='resolution_acceptances')
    op.drop_table('resolution_acceptances')
    op.drop_table('resolution_proposals')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_complaints_transaction_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_authorizations_transaction_id'), table_name='authorizations')
    op.drop_table('authorizations')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('human_checks')
    op.drop_table('fulfillments')
    op.drop_index(op.f('ix_evidence_transaction_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_chain_txs_transaction_id'), table_name='chain_txs')
    op.drop_index(op.f('ix_chain_txs_status'), table_name='chain_txs')
    op.drop_table('chain_txs')
    op.drop_index(op.f('ix_audit_events_transaction_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_transactions_state'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_provider_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_quotes_intent_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_providers_trade'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_intents_customer_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_users_privy_did'), table_name='users')
    op.drop_table('users')
    op.drop_table('kv_cursors')
    op.drop_index(op.f('ix_blockchain_events_tx_key'), table_name='blockchain_events')
    op.drop_table('blockchain_events')
    # ### end Alembic commands ###
