"""escrow intent id

Revision ID: 20078016152c
Revises: 118b2f59d296
Create Date: 2026-09-12 13:04:43.419493
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20078016152c'
down_revision: str | None = '118b2f59d296'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('escrow_intent_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint('uq_transactions_escrow_intent_id', 'transactions', ['escrow_intent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_transactions_escrow_intent_id', 'transactions', type_='unique')
    op.drop_column('transactions', 'escrow_intent_id')
    # ### end Alembic commands ###
