"""Transaction lifecycle (Blueprint §13, reconciled with the PRD). The only writer of state is services/state/machine.py."""
from enum import StrEnum


class TxState(StrEnum):
    CREATED = "CREATED"
    INTENT_STRUCTURED = "INTENT_STRUCTURED"
    QUOTE_SELECTED = "QUOTE_SELECTED"
    AWAITING_AUTHORIZATION = "AWAITING_AUTHORIZATION"
    AUTHORIZED = "AUTHORIZED"
    FUNDING = "FUNDING"
    FUNDED = "FUNDED"
    IN_PROGRESS = "IN_PROGRESS"
    EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED"
    DELIVERED = "DELIVERED"
    RELEASED = "RELEASED"
    DISPUTED = "DISPUTED"
    RESOLVING = "RESOLVING"
    PROPOSED = "PROPOSED"
    SETTLED = "SETTLED"
    ESCALATED = "ESCALATED"
    CANCELLED = "CANCELLED"


class Event(StrEnum):
    INTENT_STRUCTURED = "INTENT_STRUCTURED"
    QUOTE_SELECTED = "QUOTE_SELECTED"
    AUTHORIZATION_ISSUED = "AUTHORIZATION_ISSUED"
    AUTHORIZED = "AUTHORIZED"
    FUNDING_STARTED = "FUNDING_STARTED"
    FUNDED_ONCHAIN = "FUNDED_ONCHAIN"
    WORK_STARTED = "WORK_STARTED"
    EVIDENCE_ADDED = "EVIDENCE_ADDED"
    DELIVERED_ONCHAIN = "DELIVERED_ONCHAIN"
    RELEASED_ONCHAIN = "RELEASED_ONCHAIN"
    DISPUTE_OPENED_ONCHAIN = "DISPUTE_OPENED_ONCHAIN"
    RESPONSE_RECEIVED = "RESPONSE_RECEIVED"
    RESPONSE_TIMEOUT = "RESPONSE_TIMEOUT"
    PROPOSAL_MADE = "PROPOSAL_MADE"
    ESCALATION_REQUIRED = "ESCALATION_REQUIRED"
    SETTLED_ONCHAIN = "SETTLED_ONCHAIN"
    REJECTED = "REJECTED"
    ACCEPT_TIMEOUT = "ACCEPT_TIMEOUT"
    DECLINED = "DECLINED"
    AUTHORIZATION_EXPIRED = "AUTHORIZATION_EXPIRED"
    REFUNDED_ONCHAIN = "REFUNDED_ONCHAIN"


S, E = TxState, Event

TRANSITIONS: dict[tuple[TxState, Event], TxState] = {
    (S.CREATED, E.INTENT_STRUCTURED): S.INTENT_STRUCTURED,
    (S.INTENT_STRUCTURED, E.QUOTE_SELECTED): S.QUOTE_SELECTED,
    (S.QUOTE_SELECTED, E.AUTHORIZATION_ISSUED): S.AWAITING_AUTHORIZATION,
    (S.AWAITING_AUTHORIZATION, E.AUTHORIZED): S.AUTHORIZED,
    (S.AUTHORIZED, E.FUNDING_STARTED): S.FUNDING,
    (S.FUNDING, E.FUNDED_ONCHAIN): S.FUNDED,
    (S.FUNDED, E.WORK_STARTED): S.IN_PROGRESS,
    (S.IN_PROGRESS, E.EVIDENCE_ADDED): S.EVIDENCE_SUBMITTED,
    (S.EVIDENCE_SUBMITTED, E.DELIVERED_ONCHAIN): S.DELIVERED,
    (S.DELIVERED, E.RELEASED_ONCHAIN): S.RELEASED,
    (S.DELIVERED, E.DISPUTE_OPENED_ONCHAIN): S.DISPUTED,
    (S.DISPUTED, E.RESPONSE_RECEIVED): S.RESOLVING,
    (S.DISPUTED, E.RESPONSE_TIMEOUT): S.RESOLVING,
    (S.RESOLVING, E.PROPOSAL_MADE): S.PROPOSED,
    (S.RESOLVING, E.ESCALATION_REQUIRED): S.ESCALATED,
    (S.PROPOSED, E.SETTLED_ONCHAIN): S.SETTLED,
    (S.PROPOSED, E.REJECTED): S.ESCALATED,
    (S.PROPOSED, E.ACCEPT_TIMEOUT): S.ESCALATED,
}
# A funding tx that reverts or never lands can still be cancelled; so can anything before money moves.
for _state in (S.CREATED, S.INTENT_STRUCTURED, S.QUOTE_SELECTED, S.AWAITING_AUTHORIZATION, S.AUTHORIZED, S.FUNDING):
    TRANSITIONS[(_state, E.DECLINED)] = S.CANCELLED
    TRANSITIONS[(_state, E.AUTHORIZATION_EXPIRED)] = S.CANCELLED
# claimRefund() after expiresAt when nothing was ever submitted (no AI, no dispute).
for _state in (S.FUNDED, S.IN_PROGRESS, S.EVIDENCE_SUBMITTED):
    TRANSITIONS[(_state, E.REFUNDED_ONCHAIN)] = S.CANCELLED

TERMINAL: frozenset[TxState] = frozenset({S.RELEASED, S.SETTLED, S.CANCELLED})
CHAIN_COMMITTED: frozenset[Event] = frozenset({E.FUNDED_ONCHAIN, E.DELIVERED_ONCHAIN, E.RELEASED_ONCHAIN,
                                              E.DISPUTE_OPENED_ONCHAIN, E.SETTLED_ONCHAIN, E.REFUNDED_ONCHAIN})
PRE_FUNDING: frozenset[TxState] = frozenset({S.CREATED, S.INTENT_STRUCTURED, S.QUOTE_SELECTED, S.AWAITING_AUTHORIZATION, S.AUTHORIZED, S.FUNDING})


def next_state(state: TxState, event: Event) -> TxState | None:
    return TRANSITIONS.get((state, event))


class Role(StrEnum):
    CUSTOMER = "customer"
    PROVIDER = "provider"
    OPERATOR = "operator"


class EvidenceKind(StrEnum):
    AFTER_PHOTO = "AFTER_PHOTO"
    COMPLAINT = "COMPLAINT"
    COUNTER = "COUNTER"


class ComplaintCategory(StrEnum):
    INCOMPLETE = "INCOMPLETE"
    NOT_AS_AGREED = "NOT_AS_AGREED"
    DAMAGE = "DAMAGE"
    NO_SHOW = "NO_SHOW"
