import uuid
from typing import Optional, List
from sqlmodel import SQLModel, Field, Relationship, Column
from sqlalchemy.dialects.postgresql import JSON
from datetime import datetime

class User(SQLModel, table=True):
    """
    Represents a human user or an organizational entity on Intentra.
    Authenticates via Privy and verifies identity via World ID.
    """
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    wallet_address: str = Field(unique=True, index=True)
    world_id_nullifier: Optional[str] = Field(default=None, unique=True) # Stored as string to handle NUMERIC(78,0)
    
    email: Optional[str] = None
    full_name: Optional[str] = None
    location_data: Optional[dict] = Field(default=None, sa_column=Column(JSON))
    
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Relationships
    intents: List["Intent"] = Relationship(back_populates="user")


class Intent(SQLModel, table=True):
    """
    The core desire expressed by the user (e.g., "I need a plumber in Lagos for ₦50,000 max").
    """
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    user_id: uuid.UUID = Field(foreign_key="user.id", index=True)
    
    initiator_agent_id: Optional[str] = None # Tracks external AI agents via Bazantic
    
    description: str
    budget_max: float
    status: str = Field(default="PENDING_QUOTES") # PENDING_QUOTES, AUTHORIZED, FULFILLING, RESOLVED
    
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Relationships
    user: User = Relationship(back_populates="intents")
    quotes: List["Quote"] = Relationship(back_populates="intent")


class Quote(SQLModel, table=True):
    """
    A concrete offer generated by the AgentService based on the user's Intent.
    """
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    intent_id: uuid.UUID = Field(foreign_key="intent.id", index=True)
    
    provider_id: str # External ID or reference to the merchant/provider
    amount: float
    currency: str = Field(default="USD") # USD, NGN, HBAR
    trust_score: float = Field(default=0.0) # From The Graph
    
    is_accepted: bool = Field(default=False)
    
    # Relationships
    intent: Intent = Relationship(back_populates="quotes")
    transaction: Optional["Transaction"] = Relationship(back_populates="quote")


class Transaction(SQLModel, table=True):
    """
    The financial lifecycle state machine. Created when a user cryptographically signs a Quote.
    """
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    quote_id: uuid.UUID = Field(foreign_key="quote.id", unique=True)
    
    status: str = Field(default="LOCKED") # LOCKED, FULFILLMENT_SUBMITTED, DISPUTED, COMPLETED
    escrow_tx_hash: Optional[str] = None # Hedera transaction hash
    
    # Relationships
    quote: Quote = Relationship(back_populates="transaction")
    payment: Optional["Payment"] = Relationship(back_populates="transaction")


class Payment(SQLModel, table=True):
    """
    Tracking the actual fiat/crypto payment rail execution (e.g., Moove Virtual Card).
    """
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    transaction_id: uuid.UUID = Field(foreign_key="transaction.id", unique=True)
    
    moove_link_id: Optional[str] = None
    payment_status: str = Field(default="PENDING")
    
    # Relationships
    transaction: Transaction = Relationship(back_populates="payment")
